name: Build

on:
  - push
  - pull_request

jobs:
  test-make-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up openJDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Gradle
        run: make build